version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    env_file:
      - .env
    environment:
      FLASK_ENV: production
    links:
      - redis
  redis:
    image: "redis:alpine"
volumes:
  logvolume01: {}
